### ISSUE TITLE
Layout algorithm needs a couple frames to stabilize

### ISSUE THREAD

**Issue by gregsn** [vvvv-dottore/Elementa#54]
> just had a look at All At Once. I pressed F8 and then F6 to see what happens in the first frames. It looks like the first 3 frames are wrong. I wonder where these frame delay issues come from and if we can drop the number of frames needed for startup.

**Comment by natan-sinigaglia** [comment]
ok i got the problem:
the way the Columns node work is that it checks for the size of the window to get the column height and assign the elementa to columns.
the problem is that the render size comes with a framedelay.
i tried to solve it using ClientBounds node but it's not really usefull: it returns the bounds only after the first notification is fired. so when you open the patch it doesn't return the size, you need to move the mouse over the renderer at least.
I wanted to get the clientBounds from the renderer itself (using ClientBounds operation) but I can't use that operation in the patch. how can i do it? (I already referenced UI.Form)
![image](https://user-images.githubusercontent.com/6460926/79042549-05a51700-7bf9-11ea-877a-1de02984913b.png)

**Comment by gregsn** [comment]
indeed. I'm on it. In the patch itself, you'd also need to get rid of the ClientBounds pads, which are introducing yet another frame delay. But 2 of the 3 incorrect frames are indeed caused by the renderer.

**Comment by gregsn** [comment]
that should behave better in 2020.1.2. TODO; check that patch again and use ClientBounds node to influence the layout

**Comment by natan-sinigaglia** [comment]
![image](https://user-images.githubusercontent.com/6460926/83445514-67da0580-a44d-11ea-9a97-cdcebfcdcdf2.png)

I don't get the ClientBounds node.
Am I using it wrong?

**Comment by gregsn** [comment]
Sorry. No you are not doing anything wrong. The ClientBounds got fixed for 2020.1.2 but some unfortunate event lead to not making the fix through. 2020.1.3 is being worked on

**Comment by natan-sinigaglia** [comment]
ClientBounds works fine now.
there's still a framedelay, which is impossible to get rid of.
the solution is that The root doesn't draw in the first frame, to give time to the layout nodes to operate on startup
